import java.util.ArrayList;

	/**
	 * <h1> Book.java </h1>
	 * This class contains a constructor that creates an object 
	 * to store all of the attributes for all for each book.
	 * 
	 * @author Austin
	 * @version 1.0
	 * @since 1-28-2021
	 */

public class Book {

	//Create the private variables to store all of the attributes all all eBooks.
	private String title;
	private String author;
	private int yearWritten;
	private String edition;
	private Double price;
	private String bookContent;
	
	/**
	 * This is the default constructor for the Book.java class. This constructor 
	 * creates a object for each book, these objects are automatically generated by the driver
	 * class. This class also stores to raw content for each book.
	 * 
	 * @param title		This String variable sets the field value of the title for the 
	 * 					book object.
	 * @param author	This String variable sets the field value of the author name for
	 * 					the book object.
	 * @param yearWritten	This int variable sets the field value of the publishing year
	 * 						for the book object.
	 * @param edition	This String variable sets the field value of the edition for the 
	 * 						book object.
	 * @param price		This double variable sets the field value of the price for the book object.
	 * @param bookContent	This is a string variable set the field value of the bookContent. 
	 */

	public Book(String title, String author, int yearWritten, String edition,
		Double price, String bookContent) {
		this.title = title;
		this.author = author;
		this.yearWritten = yearWritten;
		this.edition = edition;
		this.price = price;
		this.bookContent = bookContent;
	}
	
	/**
	 * This is a getter method that return the string value for the field title.
	 * @return This is the value of the variable title.
	 */
	public String getTitle()
	{
		return title;
	}
	
	/**
	 * This is a setter method that sets the value of the string variable title.
	 * @param title	This String variable changes the field value of title.
	 */
	public void setTitle(String title)
	{
		this.title = title;
	}
	
	/**
	 * This is a getter method that returns the String value for the field author.
	 * @return This is the value of the variable author.
	 */
	public String getAuthor()
	{
		return author;
	}
	
	/**
	 * This is a setter method that sets the value of the String variable author.
	 * @param author This String variable changes the field value of author.
	 */
	public void setAuthor(String author)
	{
		this.author = author;
	}
	
	/**
	 * This is a getter method that returns the int value for the field yearWritten.
	 * @param yearWritten This is the value of the variable yearWritten.
	 */
	public int getYearWritten()
	{
		return yearWritten;
	}
	
	/**
	 * This is a setter method that sets the value of the int variable yearWritten.
	 * @param author This int variable changes the field value of yearWritten.
	 */
	public void setYearWritten(int yearWritten)
	{
		this.yearWritten = yearWritten;
	}
	
	/**
	 * This is getter method that returns the String value for the field edition.
	 * @return This is the value of the variable edition.
	 */
	public String getEdition()
	{
		return edition;
	}
	
	/**
	 * This is a setter method that sets the value of the String variable edition.
	 * @param edition This String variable changes the field value of edition.
	 */
	public void setEdition(String edition)
	{
		this.edition = edition;
	}
	
	/**
	 * This is a getter method that returns the double value for the field price.
	 * @return This is the value of the variable price.
	 */
	public double getPrice()
	{
		return price;
	}
	
	/**
	 * This is a setter method that sets the value of the double variable price.
	 * @param price	This double variable changes the field value of price.
	 */
	public void setPrice(double price)
	{
		this.price = price;
	}
	
	/**
	 * This is method returns String containing a purchase notification for every time a
	 * user purchases a book.
	 * @return This is a string with a aggregated message stating a successful purchase has been completed.
	 */
	public String getPurchaseNotification()
	{
		return "[$] eBook Purchase Successful.\n[i] To read this eBook, "
				+ "please use the \"read book #\" command, or to return, use the \"return book #\" command."
				+ "\n[$] Thank You for your Purchase of \""+getTitle()
				+" by "+getAuthor()+", published in "+getYearWritten()
				+", Edition: "+getEdition()+"\" For $"+getPrice()+".";
	}
	
	/**
	 * This is method returns String containing a return notification for every time a
	 * user returns a PURCHASED eBook.
	 * @return This is a string with a aggregated message stating a successful return of a purchase eBook has been completed.
	 */
	public String getReturnNotification()
	{
		return "[$] eBook Return Successful.\n"
				+"[$] You no longer own \""+getTitle()+" by "+getAuthor()+", published in "+getYearWritten()
				+", Edition: "+getEdition()+".\"";
	}
	
	/**
	 * This method returns the field String value of bookContent.
	 * @return This is a String with the content of each book object.
	 */
	public String getBookContent()
	{
		return bookContent;
	}
	
	/**
	 * This is a toString() method that returns all data from each book object
	 * @return A String value that shows all of the data for each book object.
	 */
	public String toString()
	{
		return getTitle()+" by "
				+getAuthor()+", published in "+getYearWritten()
				+", Edition: "+getEdition()+" | Price: $"+getPrice();
	}
	
	
}
